version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          TEST_COVERAGE: true

    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run tests
          command: bundle exec rake

      - store_artifacts:
          path: coverage
          destination: coverage
